- name: disable and enable default redis
  ansible.builtin.shell: dnf module disable redis -y ; dnf module enable redis:7 -y

- name: install redis server
  ansible.builtin.dnf:
    name: redis
    state: present

- name: replace protected mode line from yes to no
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: 'protected-mode no'

- name: replace with local host to allow remote connections
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable redis service
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes