- name: install maven and mysql
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - mysql
  - maven

- name: install pymysql and cryptography
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
  - PyMYSQL
  - cryptography

- name: install maven dependencies
  ansible.builtin.command: mvn clean package
  args:
      chdir: /app
    
- name: rename jar file
  ansible.builtin.command: mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app