- name: disable and enable nginx configuration
    ansible.builtin.shell: dnf module disable nginx -y ; dnf module enable nginx:1.24 -y

- name: install nginx server
  ansible.builtin.dnf:
    name: nginx
    state: present
  
- name: start and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes